# Generated by Django 6.0.3 on 2026-03-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_url", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="short_code",
            field=models.CharField(db_index=True, max_length=7, unique=True),
        ),
    ]
