# Generated by Django 6.0.3 on 2026-03-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("short_url", "0002_alter_shorturl_short_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shorturl",
            name="expired_at",
        ),
    ]
