# Generated by Django 6.0.3 on 2026-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_url", "0003_remove_shorturl_expired_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="click",
            name="country",
        ),
        migrations.AddField(
            model_name="click",
            name="country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
