# Generated by Django 6.0.3 on 2026-03-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_url", "0004_remove_click_country_click_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="click",
            name="referer_domain",
            field=models.CharField(default="direct", max_length=255),
            preserve_default=False,
        ),
    ]
