# Generated by Django 6.0.3 on 2026-04-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("short_url", "0005_click_referer_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="click",
            name="clicked_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["short_url", "clicked_at", "country_code"],
                name="clicks_short_u_ea86ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["short_url", "clicked_at", "device_type"],
                name="clicks_short_u_656119_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["short_url", "clicked_at", "referer_domain"],
                name="clicks_short_u_e544cf_idx",
            ),
        ),
    ]
