# Generated by Django 6.0.3 on 2026-07-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_options_remove_customuser_username_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otpverifications",
            name="expired_at",
        ),
        migrations.RemoveField(
            model_name="otpverifications",
            name="is_used",
        ),
        migrations.RemoveField(
            model_name="otpverifications",
            name="otp",
        ),
        migrations.AddField(
            model_name="otpverifications",
            name="otp_hash",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="otpverifications",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="otpverifications",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
