name: Django CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DEBUG: "False"
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_NAME: testdb
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_HOST: localhost
      DB_PORT: 5432
      REDIS_URL: redis://localhost:6379

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: ./src
        run: python manage.py test
      - name: Check formatting
        working-directory: ./src
        run: |
          black --check .
          isort --check-only .


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/url-shortener
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            cd src
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn && echo "Gunicorn restarted successfully" || exit 1
